- hosts: localhost
  gather_facts: false
  become: false
  tasks:

  - uri:
      url: http://127.0.0.1:5000
    register: the_call
    until: "{{ the_call.json | all_data_processing_containers_are_stopped }}"
    retries: 100
    delay: 1
  
  - debug:
      msg: "{{ the_call.json }}"